# Generated by Django 4.2.27 on 2026-03-09 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/')),
                ('bio', models.CharField(blank=True, max_length=200, verbose_name='个人简介')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], default='other', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='所在地')),
                ('website', models.URLField(blank=True, verbose_name='个人网站')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='粉丝数')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='关注数')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='笔记数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '关注',
                'verbose_name_plural': '关注',
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
